const STYLE_DATA = [
  {
    id: "ink-wash",
    nameZh: "文人水墨",
    nameEn: "Literati Ink Painting",
    type: "地域传统",
    period: "10–19 世纪",
    year: 1050,
    region: "东亚",
    track: "东亚视觉传统",
    summary: "以笔墨、气韵与留白表达主观精神，而非复制可见世界。",
    recognition: "墨色浓淡、书写性笔触、大面积留白与散点空间。",
    traits: ["有机", "留白", "低饱和", "克制"],
    fields: ["绘画", "书籍"],
    genes: {
      composition: ["散点空间", "虚实相生", "大面积留白"],
      form: ["书写性线条", "概括造型", "墨色层次"],
      color: ["墨黑", "纸白", "淡赭"],
      type: ["书法题跋", "印章点色"],
      texture: ["宣纸渗化", "干湿笔触"]
    },
    influencedBy: "中国书法、山水传统与文人思想",
    influenced: "日本南画、现代水墨、东亚极简视觉",
    related: ["ukiyo-e", "swiss"],
    palette: ["#20201d", "#ddd9cd", "#a14b37"],
    art: "ink",
    promptZh: ["文人水墨意境", "散点构图", "大面积留白", "墨色浓淡变化", "书写性笔触", "宣纸肌理"],
    promptEn: ["literati ink painting sensibility", "shifting perspective", "generous negative space", "tonal ink washes", "calligraphic brushwork", "xuan paper texture"]
  },
  {
    id: "islamic-geometry",
    nameZh: "伊斯兰几何装饰",
    nameEn: "Islamic Geometric Ornament",
    type: "地域传统",
    period: "8–19 世纪",
    year: 1100,
    region: "西亚与北非",
    track: "全球地域传统",
    summary: "通过重复、对称与比例构成可无限延展的秩序。",
    recognition: "星形多边形、互锁网格、重复镶嵌与精密边饰。",
    traits: ["几何", "对称", "满版", "精密"],
    fields: ["建筑", "装饰", "平面"],
    genes: {
      composition: ["中心对称", "连续镶嵌", "满版结构"],
      form: ["星形多边形", "互锁线带", "植物卷草"],
      color: ["钴蓝", "绿松石", "金色", "砖红"],
      type: ["书法边饰", "几何边框"],
      texture: ["釉面砖", "石膏雕刻", "马赛克"]
    },
    influencedBy: "古典几何、地方工艺与伊斯兰文化",
    influenced: "摩尔复兴、装饰艺术与当代参数化图案",
    related: ["art-nouveau", "bauhaus"],
    palette: ["#165f73", "#d6a84c", "#9f3f35"],
    art: "islamic",
    promptZh: ["伊斯兰几何装饰", "精密星形镶嵌", "中心对称", "连续互锁图案", "钴蓝与金色", "釉面砖质感"],
    promptEn: ["Islamic geometric ornament", "precise star tessellation", "radial symmetry", "interlocking pattern", "cobalt blue and gold", "glazed tile texture"]
  },
  {
    id: "renaissance",
    nameZh: "文艺复兴",
    nameEn: "Renaissance",
    type: "历史时期",
    period: "14–16 世纪",
    year: 1450,
    region: "欧洲",
    track: "欧洲艺术与现代主义",
    summary: "以透视、人体和古典秩序重新建立可测量的现实空间。",
    recognition: "稳定三角构图、线性透视、均衡人物与柔和明暗塑造。",
    traits: ["写实", "对称", "自然色", "理性"],
    fields: ["绘画", "建筑", "雕塑"],
    genes: {
      composition: ["三角构图", "单点透视", "稳定平衡"],
      form: ["理想化人体", "精确比例", "立体塑造"],
      color: ["土红", "群青", "暖肤色"],
      type: ["古典比例", "碑刻式衬线"],
      texture: ["油画薄涂", "壁画灰泥"]
    },
    influencedBy: "古希腊罗马艺术、人文主义与科学观察",
    influenced: "矫饰主义、巴洛克与学院艺术",
    related: ["baroque", "impressionism"],
    palette: ["#8e4b35", "#315477", "#c7a46a"],
    art: "renaissance",
    promptZh: ["文艺复兴绘画语境", "稳定三角构图", "精确线性透视", "理想化人体比例", "柔和明暗塑造", "油画薄涂质感"],
    promptEn: ["Renaissance painting context", "stable triangular composition", "precise linear perspective", "idealized human proportions", "soft chiaroscuro modeling", "layered oil glaze texture"]
  },
  {
    id: "baroque",
    nameZh: "巴洛克",
    nameEn: "Baroque",
    type: "艺术运动",
    period: "17 世纪",
    year: 1630,
    region: "欧洲",
    track: "欧洲艺术与现代主义",
    summary: "用戏剧光线、运动和宏大尺度制造情感冲击。",
    recognition: "强烈明暗对照、斜向运动、聚光人物与深暗背景。",
    traits: ["写实", "动态", "强对比", "戏剧"],
    fields: ["绘画", "建筑", "雕塑"],
    genes: {
      composition: ["斜向运动", "瞬间叙事", "深层空间"],
      form: ["强烈动作", "丰厚体积", "曲线结构"],
      color: ["深黑", "酒红", "金色"],
      type: ["高反差衬线", "华丽标题"],
      texture: ["厚重油彩", "丝绒与金属"]
    },
    influencedBy: "文艺复兴、宗教改革与宫廷权力",
    influenced: "洛可可、浪漫主义与戏剧性摄影",
    related: ["renaissance", "surrealism"],
    palette: ["#1d1717", "#8f2d28", "#c49b4b"],
    art: "baroque",
    promptZh: ["巴洛克戏剧性", "强烈对角线运动", "聚光式明暗对照", "深暗背景", "酒红与金色", "厚重油画质感"],
    promptEn: ["Baroque theatricality", "strong diagonal movement", "spotlit chiaroscuro", "deep dark background", "wine red and gold", "rich impasto oil texture"]
  },
  {
    id: "ukiyo-e",
    nameZh: "浮世绘",
    nameEn: "Ukiyo-e",
    type: "地域传统",
    period: "17–19 世纪",
    year: 1780,
    region: "东亚",
    track: "东亚视觉传统",
    summary: "以木版套色记录城市生活、风景与转瞬即逝的世俗世界。",
    recognition: "平涂色块、清晰轮廓、非常规裁切与压缩空间。",
    traits: ["平面", "不对称", "自然色", "叙事"],
    fields: ["版画", "插画", "海报"],
    genes: {
      composition: ["大胆裁切", "高低视点", "非对称平衡"],
      form: ["清晰轮廓", "平面色块", "图案化自然"],
      color: ["靛蓝", "朱红", "纸本米色"],
      type: ["竖排题签", "印章式标记"],
      texture: ["木版纹理", "套色轻微错位"]
    },
    influencedBy: "江户城市文化与木版印刷",
    influenced: "日本主义、印象派、新艺术运动",
    related: ["art-nouveau", "impressionism"],
    palette: ["#1b4b6c", "#d6533c", "#e8d8b8"],
    art: "ukiyo",
    promptZh: ["浮世绘木版画", "大胆边缘裁切", "平面套色色块", "清晰墨线", "靛蓝与朱红", "和纸印刷纹理"],
    promptEn: ["ukiyo-e woodblock print", "bold edge cropping", "flat registered color fields", "crisp ink outlines", "indigo and vermilion", "washi print texture"]
  },
  {
    id: "impressionism",
    nameZh: "印象主义",
    nameEn: "Impressionism",
    type: "艺术运动",
    period: "1860s–1880s",
    year: 1874,
    region: "欧洲",
    track: "欧洲艺术与现代主义",
    summary: "以可见笔触和瞬时色光捕捉现代生活中的感知经验。",
    recognition: "破碎短笔触、户外光线、彩色阴影与开放式构图。",
    traits: ["有机", "开放构图", "明亮", "轻盈"],
    fields: ["绘画"],
    genes: {
      composition: ["开放构图", "日常瞬间", "摄影式裁切"],
      form: ["短促笔触", "边缘溶解", "色彩塑形"],
      color: ["高明度蓝紫", "浅绿", "暖黄"],
      type: ["不强调文字"],
      texture: ["可见油画笔触", "湿画法"]
    },
    influencedBy: "现实主义、摄影、浮世绘与现代都市",
    influenced: "后印象主义、现代色彩理论",
    related: ["ukiyo-e", "renaissance"],
    palette: ["#7da3c7", "#9ab77a", "#e2b85c"],
    art: "impressionism",
    promptZh: ["印象主义绘画", "开放式瞬间构图", "破碎短笔触", "户外自然光", "彩色阴影", "明亮空气感"],
    promptEn: ["Impressionist painting", "open momentary composition", "broken short brushstrokes", "plein-air daylight", "colored shadows", "luminous atmosphere"]
  },
  {
    id: "art-nouveau",
    nameZh: "新艺术运动",
    nameEn: "Art Nouveau",
    type: "设计运动",
    period: "1890s–1910s",
    year: 1900,
    region: "欧洲",
    track: "商业与设计视觉",
    summary: "以植物曲线和整体设计回应工业时代的机械化生产。",
    recognition: "鞭状曲线、花叶结构、装饰边框与图文一体。",
    traits: ["有机", "满版", "低饱和", "装饰"],
    fields: ["海报", "建筑", "产品"],
    genes: {
      composition: ["装饰边框", "图文融合", "垂直延展"],
      form: ["鞭状曲线", "植物卷须", "修长人物"],
      color: ["橄榄绿", "赭石", "柔金"],
      type: ["手绘曲线字体", "装饰首字母"],
      texture: ["平版印刷", "彩色玻璃", "金属线条"]
    },
    influencedBy: "工艺美术运动、浮世绘、自然形态",
    influenced: "装饰艺术、现代海报与有机设计",
    related: ["ukiyo-e", "islamic-geometry"],
    palette: ["#5f7550", "#b96c49", "#d2b56c"],
    art: "nouveau",
    promptZh: ["新艺术运动海报", "鞭状植物曲线", "装饰边框", "图文一体", "橄榄绿与柔金", "复古平版印刷"],
    promptEn: ["Art Nouveau poster", "whiplash botanical curves", "ornamental border", "integrated image and lettering", "olive green and soft gold", "vintage lithographic print"]
  },
  {
    id: "constructivism",
    nameZh: "构成主义",
    nameEn: "Constructivism",
    type: "艺术与设计运动",
    period: "1915–1930s",
    year: 1920,
    region: "欧洲",
    track: "欧洲艺术与现代主义",
    summary: "以几何、工业语言和宣传性构图把艺术投入社会行动。",
    recognition: "斜向轴线、红黑高对比、摄影拼贴与粗体文字。",
    traits: ["几何", "不对称", "强对比", "反叛"],
    fields: ["海报", "摄影", "建筑"],
    genes: {
      composition: ["强对角线", "不对称", "动态层叠"],
      form: ["几何形", "摄影拼贴", "放射线"],
      color: ["红", "黑", "纸白"],
      type: ["粗体无衬线", "倾斜排版"],
      texture: ["粗粝印刷", "纸张颗粒"]
    },
    influencedBy: "立体主义、未来主义与工业生产",
    influenced: "包豪斯、政治海报与实验排版",
    related: ["bauhaus", "swiss"],
    palette: ["#df2e24", "#171715", "#e7dfca"],
    art: "constructivism",
    promptZh: ["构成主义平面设计", "强烈斜向构图", "几何形与摄影拼贴", "红黑高对比", "粗体无衬线文字", "粗粝印刷质感"],
    promptEn: ["Constructivist graphic design", "forceful diagonal composition", "geometric forms and photomontage", "red black high contrast", "bold sans-serif typography", "rough print texture"]
  },
  {
    id: "bauhaus",
    nameZh: "包豪斯",
    nameEn: "Bauhaus",
    type: "设计运动",
    period: "1919–1933",
    year: 1925,
    region: "欧洲",
    track: "商业与设计视觉",
    summary: "以基础形、材料实验与功能原则统一艺术、工艺和工业。",
    recognition: "圆方三角、原色、清晰层级与功能导向的非对称版式。",
    traits: ["几何", "不对称", "原色", "理性"],
    fields: ["平面", "建筑", "产品"],
    genes: {
      composition: ["非对称平衡", "功能分区", "清晰层级"],
      form: ["圆方三角", "模块化", "机器几何"],
      color: ["红", "黄", "蓝", "黑"],
      type: ["几何无衬线", "小写实验"],
      texture: ["平面印刷", "钢与玻璃"]
    },
    influencedBy: "构成主义、风格派与工艺教育",
    influenced: "现代主义建筑、企业设计、界面系统",
    related: ["constructivism", "swiss"],
    palette: ["#d93a2f", "#efbd2f", "#2459a9"],
    art: "bauhaus",
    promptZh: ["包豪斯设计语言", "圆方三角基础形", "功能主义非对称版式", "红黄蓝原色", "几何无衬线字体", "平面印刷"],
    promptEn: ["Bauhaus design language", "circle square triangle primitives", "functional asymmetrical layout", "red yellow blue primaries", "geometric sans-serif typography", "flat print finish"]
  },
  {
    id: "surrealism",
    nameZh: "超现实主义",
    nameEn: "Surrealism",
    type: "艺术运动",
    period: "1920s–1940s",
    year: 1930,
    region: "欧洲",
    track: "欧洲艺术与现代主义",
    summary: "把梦境、潜意识和偶然性带入看似真实却逻辑失常的世界。",
    recognition: "写实物体的反常组合、尺度错置、空旷空间与梦境光线。",
    traits: ["写实", "中心构图", "冷色", "梦境"],
    fields: ["绘画", "摄影", "电影"],
    genes: {
      composition: ["空旷舞台", "尺度错置", "悬浮关系"],
      form: ["物体变形", "不可能组合", "象征物"],
      color: ["冷蓝", "沙色", "低饱和红"],
      type: ["克制标题", "拼贴文字"],
      texture: ["光滑写实", "梦境薄雾"]
    },
    influencedBy: "达达主义、精神分析与形而上绘画",
    influenced: "观念摄影、广告与奇幻影像",
    related: ["baroque", "pop-art"],
    palette: ["#7a9fbb", "#d0b27b", "#9e514a"],
    art: "surrealism",
    promptZh: ["超现实主义梦境", "空旷舞台式构图", "日常物体反常组合", "尺度错置", "冷静写实光线", "低饱和神秘色彩"],
    promptEn: ["Surrealist dreamscape", "empty stage-like composition", "uncanny combination of ordinary objects", "dislocated scale", "cool realistic lighting", "muted mysterious palette"]
  },
  {
    id: "swiss",
    nameZh: "瑞士国际主义",
    nameEn: "International Typographic Style",
    type: "设计运动",
    period: "1950s–1960s",
    year: 1955,
    region: "欧洲",
    track: "商业与设计视觉",
    summary: "以网格、无衬线字体和客观信息层级建立现代视觉秩序。",
    recognition: "严格网格、左对齐、无衬线字体、留白和少量强调色。",
    traits: ["几何", "网格", "留白", "理性"],
    fields: ["海报", "书籍", "品牌"],
    genes: {
      composition: ["模数网格", "左对齐", "大量留白"],
      form: ["客观摄影", "几何信息块"],
      color: ["黑白", "单一强调色"],
      type: ["无衬线字体", "清晰字号层级"],
      texture: ["干净胶印", "平滑纸面"]
    },
    influencedBy: "包豪斯、构成主义与新字体运动",
    influenced: "企业识别、信息设计与数字界面",
    related: ["bauhaus", "constructivism"],
    palette: ["#f2f2ef", "#161616", "#e04435"],
    art: "swiss",
    promptZh: ["瑞士国际主义海报", "严格模数网格", "左对齐无衬线排版", "大面积留白", "黑白与单一红色强调", "客观信息层级"],
    promptEn: ["International Typographic Style poster", "strict modular grid", "left-aligned sans-serif typography", "generous negative space", "black white with one red accent", "objective information hierarchy"]
  },
  {
    id: "pop-art",
    nameZh: "波普艺术",
    nameEn: "Pop Art",
    type: "艺术运动",
    period: "1950s–1970s",
    year: 1962,
    region: "欧美",
    track: "商业与设计视觉",
    summary: "把广告、漫画与消费品图像带入艺术，放大大众传播的魅力和矛盾。",
    recognition: "高饱和原色、粗黑轮廓、网点、重复图像与商业符号。",
    traits: ["平面", "满版", "高饱和", "戏剧"],
    fields: ["绘画", "海报", "广告"],
    genes: {
      composition: ["图像重复", "近距离裁切", "漫画分格"],
      form: ["粗黑轮廓", "商业符号", "扁平人物"],
      color: ["高饱和红黄蓝", "强互补色"],
      type: ["漫画拟声字", "广告粗体"],
      texture: ["半调网点", "丝网印刷"]
    },
    influencedBy: "大众传媒、广告、漫画与达达主义",
    influenced: "后现代平面、街头艺术与网络表情文化",
    related: ["surrealism", "memphis"],
    palette: ["#f13b2d", "#f2d43d", "#1f65c1"],
    art: "pop",
    promptZh: ["波普艺术海报", "漫画式近距离裁切", "粗黑轮廓", "高饱和原色", "半调网点", "丝网印刷质感"],
    promptEn: ["Pop Art poster", "comic-style close crop", "heavy black outlines", "saturated primary colors", "halftone dots", "screen-print texture"]
  },
  {
    id: "memphis",
    nameZh: "孟菲斯",
    nameEn: "Memphis Design",
    type: "设计运动",
    period: "1981–1988",
    year: 1983,
    region: "欧洲",
    track: "商业与设计视觉",
    summary: "用鲜艳图案、廉价材料和玩笑般造型反抗现代主义的克制。",
    recognition: "彩色几何、波浪线、点阵纹样、冲突比例与不稳定平衡。",
    traits: ["几何", "不对称", "高饱和", "反叛"],
    fields: ["产品", "平面", "空间"],
    genes: {
      composition: ["碎片散布", "不稳定平衡", "舞台式陈列"],
      form: ["几何积木", "波浪与锯齿", "拟物玩笑"],
      color: ["亮粉", "青绿", "黄", "黑白"],
      type: ["几何展示字", "不规则排列"],
      texture: ["层压板", "塑料", "点阵图案"]
    },
    influencedBy: "波普艺术、装饰艺术与激进设计",
    influenced: "1990 年代平面、玩具设计与新孟菲斯",
    related: ["pop-art", "y2k"],
    palette: ["#ec4c81", "#28a99a", "#f2cc34"],
    art: "memphis",
    promptZh: ["孟菲斯设计", "碎片化不对称构图", "彩色几何积木", "波浪线与点阵", "亮粉青绿与黄色", "俏皮塑料质感"],
    promptEn: ["Memphis design", "fragmented asymmetrical composition", "colorful geometric blocks", "squiggles and dotted patterns", "hot pink teal and yellow", "playful laminate texture"]
  },
  {
    id: "brutalism",
    nameZh: "数字新粗野主义",
    nameEn: "Digital Neo-Brutalism",
    type: "数字视觉趋势",
    period: "2010s–至今",
    year: 2016,
    region: "全球",
    track: "数字与网络审美",
    summary: "用裸露结构、系统字体和故意直接的界面反对过度精致与同质化。",
    recognition: "粗边框、硬阴影、默认控件感、巨大文字与明显网格。",
    traits: ["几何", "网格", "强对比", "反叛"],
    fields: ["数字界面", "品牌", "海报"],
    genes: {
      composition: ["裸露网格", "大字号占位", "块状分区"],
      form: ["矩形边框", "系统控件", "直接符号"],
      color: ["黑白", "荧光强调色"],
      type: ["系统无衬线", "等宽字体", "巨大标题"],
      texture: ["硬边", "无修饰数字表面"]
    },
    influencedBy: "粗野主义建筑、早期网页与朋克出版",
    influenced: "独立品牌、实验网页与反设计趋势",
    related: ["swiss", "y2k"],
    palette: ["#f0ef3d", "#171715", "#f7f7f4"],
    art: "brutalism",
    promptZh: ["数字新粗野主义", "裸露块状网格", "巨大系统字体", "粗黑边框", "荧光黄与黑白", "直接无修饰界面感"],
    promptEn: ["digital neo-brutalism", "exposed block grid", "oversized system typography", "heavy black borders", "acid yellow black and white", "raw unpolished interface aesthetic"]
  },
  {
    id: "y2k",
    nameZh: "Y2K 未来复古",
    nameEn: "Y2K Futurism",
    type: "数字视觉趋势",
    period: "1997–2005 / 当代复兴",
    year: 2000,
    region: "全球",
    track: "数字与网络审美",
    summary: "以千禧年前后的技术乐观、液态金属和早期数字界面想象未来。",
    recognition: "银色镀铬、半透明塑料、椭圆轨道、像素字体与高光渐变。",
    traits: ["有机", "中心构图", "冷色", "未来"],
    fields: ["数字界面", "时尚", "品牌"],
    genes: {
      composition: ["中心悬浮", "界面叠层", "椭圆轨道"],
      form: ["液态曲面", "气泡按钮", "金属符号"],
      color: ["银色", "冰蓝", "荧光绿"],
      type: ["像素字体", "延展无衬线"],
      texture: ["镀铬", "透明塑料", "数字高光"]
    },
    influencedBy: "早期互联网、电子消费品与锐舞文化",
    influenced: "当代时尚、音乐视觉与生成式 3D",
    related: ["memphis", "brutalism"],
    palette: ["#b9c7d6", "#65d6e8", "#c8ee52"],
    art: "y2k",
    promptZh: ["Y2K 未来复古", "中心悬浮构图", "液态镀铬形体", "半透明塑料界面", "冰蓝与荧光绿", "早期数字高光"],
    promptEn: ["Y2K retrofuturism", "centered floating composition", "liquid chrome forms", "translucent plastic interface", "ice blue and acid green", "early digital glossy highlights"]
  }
];

const FILTER_GROUPS = {
  type: ["历史时期", "艺术运动", "艺术与设计运动", "设计运动", "地域传统", "数字视觉趋势"],
  region: ["欧洲", "东亚", "西亚与北非", "欧美", "全球"],
  traits: ["几何", "有机", "写实", "平面", "网格", "留白", "不对称", "对称", "强对比", "高饱和", "低饱和", "理性", "戏剧", "反叛", "未来"],
  fields: ["绘画", "海报", "平面", "建筑", "产品", "数字界面"]
};

const TIMELINE_BOUNDS = { min: -1400, max: 2025 };
